# -*- encoding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Website',
    'category': 'Website',
    'summary': '',
    'website': '',
    'version': '12.0',
    'description': "",
    'depends': [
                'website',
                'pragtech_create_static_webpages',
                ],
    'installable': True,
    'data': [
        'security/ir.model.access.csv',

        'data/website_data.xml',

        'views/assets.xml',
        'views/remove_footer.xml',
        'views/flatmates_view.xml',
        'views/config_master_view.xml',

        'static/src/xml/menu_item.xml',
        'static/src/xml/home_view.xml',
        'static/src/xml/shortlist_template.xml',
        'static/src/xml/list_place_template.xml',
        'static/src/xml/find_place_template.xml',
        'static/src/xml/about_template.xml',
        'static/src/xml/property_detail.xml',


        'static/src/xml/info_li_list.xml',
        'static/src/xml/info_template.xml',
        'static/src/xml/info_flatmate_inspection.xml',
        'static/src/xml/info_how_to_contact.xml',
        'static/src/xml/info_home_share_melbourne.xml',
        'static/src/xml/info_message_response_rate.xml',
        'static/src/xml/info_verification.xml',
        'static/src/xml/info_frequently_asked_questions.xml',
        'static/src/xml/info_why_upgrade.xml',
        'static/src/xml/info_how_does_it_work.xml',
        'static/src/xml/info_find_share_accommodation.xml',
        'static/src/xml/info_rent_your_spare_room.xml',
        'static/src/xml/info_teamups.xml',
        'static/src/xml/info_value_my_room.xml',
        'static/src/xml/info_legal_introduction.xml',
        'static/src/xml/info_holding_deposits.xml',
        'static/src/xml/info_share_accommodation_legal_situations.xml',
        'static/src/xml/info_planning_rules.xml',
        'static/src/xml/info_pre_agreement_checklist.xml',
        'static/src/xml/info_flatmate_agreement.xml',
        'static/src/xml/info_bonds.xml',
        'static/src/xml/info_condition_reports.xml',
        'static/src/xml/info_tenancy_agreements.xml',
        'static/src/xml/info_rent_payments.xml',
        'static/src/xml/info_rights_obligations.xml',
        'static/src/xml/info_ending_tenancy.xml',
        'static/src/xml/info_resolving_disputes.xml',
        'static/src/xml/info_about.xml',
        'static/src/xml/info_terms.xml',
        'static/src/xml/info_live_rent_free.xml',
        'static/src/xml/info_press.xml',
        'static/src/xml/info_community_charter.xml',
        'static/src/xml/info_privacy.xml',
        'static/src/xml/info_contact.xml',
    ],
    'application': True,
    'uninstall_hook': 'uninstall_hook',
}
